#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use App\Command\HashCommand;
use App\Command\CreateMigration;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new HashCommand());
$app->add(new CreateMigration());



$app->run();
