#!/usr/bin/env php

<?php
define('__APP_ROOT__',__DIR__) ;

require_once __DIR__ . '/vendor/autoload.php';


use \Slim\App;
require __DIR__.'/bootstrap/bootstrap.php';

require __DIR__.'/config/settings.php';
$app = new App($config);
require_once __DIR__.'/bootstrap/dependencies.php';

use Phpmig\Console\Command;


use App\Command\HashCommand;
use App\Command\MakeMigration;
use App\Command\MigrateCommand;
use App\Command\MakeController;
use App\Command\MakeModel;
use App\Command\MakeTestCommand;
use App\Command\RunTestCommand;
use App\Command\MigrationStatusCommand;
use App\Command\MigrateRollbackCommand;
use Symfony\Component\Console\Application;


$app = new Application();

$app->add(new HashCommand());
$app->add(new MakeMigration());
$app->add(new MigrateCommand());
$app->add(new MakeController());
$app->add(new MakeModel());
$app->add(new MakeTestCommand());
$app->add(new RunTestCommand());
$app->add(new MigrationStatusCommand());
$app->add(new MigrateRollbackCommand());



$app->run();
