#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';


use \Slim\App;
require __DIR__.'/bootstrap/bootstrap.php';

require __DIR__.'/config/settings.php';
$app = new App($config);
require_once __DIR__.'/bootstrap/dependencies.php';

use Phpmig\Console\Command;


use App\Command\HashCommand;
use App\Command\MakeMigration;
use App\Command\MigrateCommand;
use Symfony\Component\Console\Application;


$app = new Application();

$app->add(new HashCommand());
$app->add(new MakeMigration());

$app->addCommands(array(
    new Command\InitCommand(),
    new Command\StatusCommand(),
    new Command\CheckCommand(),
    new Command\GenerateCommand(),
    new Command\UpCommand(),
    new Command\DownCommand(),
    new Command\MigrateCommand(),
    new Command\RollbackCommand(),
    new Command\RedoCommand()
));






$app->run();
